In [1]:
# Assignment - Internal (Python for fun)

In [2]:
import pandas as pd
import numpy as np

Question 1
Add 10 to list l1 given above

In [3]:
# Append item to list 
l1 = ['learning', "Python", 'is fun?', True]
l1.append("10")
print(l1)

['learning', 'Python', 'is fun?', True, '10']


Question 2
Remove 10 from l1.

In [4]:
# Remove item from list 
l1.remove("10")
print(l1)

['learning', 'Python', 'is fun?', True]


Question 3
[ Hint: Use + operator or extend]

In [6]:
# Add two lists 
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))
# Attempt through + operator
l3 = l1+l2
l3
# Attempt through extend operator
l1.extend(l2)
print(l1)

['learning', 'Python', 'is fun?', True, 'learning', 'for', 'life', True]


Question 4
Find Range and Mean of l3.

l3 = [2,4,6,8]

[ Hint: Use len(),sum(), min(), max() functions ]

In [8]:
#print(sum(l3))
#print(max(l3))
#print(min(l3))
l3 = [2,4,6,8]

# Range 
print("The range is ",max(l3) - min(l3))

def Average(lst): 
    return sum(lst) / len(lst)

average = Average(l3)
print("The average is ",average)

The range is  6
The average is  5.0


In [9]:
# Count the occurances of an element in a given list.n
for item in l3:
    print("Occurence of item",item,"is:",l3.count(item))
    

Occurence of item 2 is: 1
Occurence of item 4 is: 1
Occurence of item 6 is: 1
Occurence of item 8 is: 1


Question 5
Append the given sequence of numbers to l3 (given above) 0,1,3,3,5,5,7,9. Count the occurences of 5 in l3.

[ Hint: Use + operator to add multiple elements in the array and count() function to print the occurences]

In [18]:
# Append the given sequence of numbers to l3 (given above) 0,1,3,3,5,5,7,9. Count the occurences of 5 in l3.
l3 = [2,4,6,8]
new_list = [0,1,3,3,5,5,7,9]
l3 = l3 + new_list

# Get the count of all the elements :
for item in l3:
    print("Occurence of item",item,"is:",l3.count(item))
    
print(l3)

Occurence of item 2 is: 1
Occurence of item 4 is: 1
Occurence of item 6 is: 1
Occurence of item 8 is: 1
Occurence of item 0 is: 1
Occurence of item 1 is: 1
Occurence of item 3 is: 2
Occurence of item 3 is: 2
Occurence of item 5 is: 2
Occurence of item 5 is: 2
Occurence of item 7 is: 1
Occurence of item 9 is: 1
[2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]


Question 6
sort and print l3 in ascending and descending order sequentially (given above)

(Hint: Use .sort() function)

In [27]:
# Sort the list in ascending and descending order
l4=[2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]

l4.sort()

# Sorted ascending results
print("The sorted list in ascending order is")
print(l4)

#sorted in reverse order

l4.sort(reverse=True)
print("The sorted list in descending order is")
print(l4)

The sorted list in ascending order is
[0, 1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 9]
The sorted list in descending order is
[9, 8, 7, 6, 5, 5, 4, 3, 3, 2, 1, 0]


In [30]:
# Question 7 - Define a function with name sum_3 which can take 3 numbers as input, and returns sum of them.

def sum_3():
    
    a = int(input("Enter First Number:"))
    b = int(input("Enter Second Number:"))
    c = int(input("Enter Third Number:"))
    
    # Get the sum 
    print("Sum of three numbers is :", a + b + c)
    
sum_3()

Enter First Number:3
Enter Second Number:4
Enter Third Number:5
Sum of three numbers is : 12


In [31]:
# Question 8
#Write the same above sum_3 function using lambda.
sum_3 = lambda a,b,c: (a+b+c)
print(sum_3(1,4,4))

9


1. Arrays in NumPy: NumPy’s main object is the homogeneous multidimensional array.

It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
In NumPy dimensions are called axes. The number of axes is rank.
NumPy’s array class is called ndarray. It is also known by the alias array.

In [32]:
# Python program to demonstrate  
# basic array characteristics 
  
# Creating array object 
arr = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] ) 
  
# Printing type of arr object 
print("Array is of type: ", type(arr)) 
  
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 
  
# Printing shape of array 
print("Shape of array: ", arr.shape) 
  
# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 
  
# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [37]:
a = np.zeros((10, 2))
a


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [42]:

#Question 1
#Create an identity 2d-array or matrix (with ones across the diagonal).
b=np.eye(5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Question 2
Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: np.matrix() function

In [43]:
c = np.matrix('9 8 7; 6 5 4; 3 2 1')
print(c)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


Question 3
Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose .T)

In [44]:
c1 = c.T
c1

matrix([[9, 6, 3],
        [8, 5, 2],
        [7, 4, 1]])

Question 4
Add + 1 to all the elements in the given matrix

In [45]:
d=c+1
d

matrix([[10,  9,  8],
        [ 7,  6,  5],
        [ 4,  3,  2]])

Question 5
Find the mean of all elements in the given matrix nd6. nd6 = [[ 1 4 9 121 144 169] [ 16 25 36 196 225 256] [ 49 64 81 289 324 361]]

Use: .mean() function

In [47]:
nd6 = np.matrix([[1,4,9,121,144,169],
                 [16,25,36,196,225,256],
                 [49,64,81,289,324,361]])
matrix_avg = nd6.mean()
print("The average of all elements of the matrix is", matrix_avg) 

The average of all elements of the matrix is 131.66666666666666


Question 7
Find the dot product of two given matrices.

[Hint: Use np.dot()]

In [48]:
d = np.matrix('1 2 3; 4 5 6; 7 8 91')
print(d)
np.dot(c,d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 91]]


matrix([[ 90, 114, 712],
        [ 54,  69, 412],
        [ 18,  24, 112]])

In [49]:
nd6.shape

(3, 6)

In [50]:
c.shape

(3, 3)

In [53]:
#Example

series1 = pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])
series1

key1    1
key2    2
key3    3
dtype: int64

In [ ]:
Question 1
Convert a given dict to pd series.m

In [51]:
# Pandas


d1 = {'a': 1, 'b': 2, 'c': 3}
series = pd.Series(d1) 
series

a    1
b    2
c    3
dtype: int64

Question 2
Find the dot product of both the series create above

[ Hint: Use np.dot() ]

In [54]:
series2 = np.dot(series, series1)
series2

14

In [55]:
# Example
d1 = {'a': [1,2,3], 'b': [3,4,5], 'c':[6,7,8] }
df1 = pd.DataFrame(d1)
df1

a  b  c
0  1  3  6
1  2  4  7
2  3  5  8

Question 3
Select second row in the above dataframe df1.

In [56]:
df1.iloc[1,]

a    2
b    4
c    7
Name: 1, dtype: int64

Question 4
Select column c in second row of df1.

[ Hint: For using labels use df.loc[row, column]. For using numeric indexed use df.iloc[]. For using mixture of numeric indexes and labels use df.ix[row, column] ]

In [57]:
df1.loc[1,'c']

7

In [61]:
# Reading a dataset from a csv file using pandas.
mtcars = pd.read_csv('mtcars.csv')
mtcars.head()


name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

Question 5
Check the type and dimensions of given dataset - mtcars.

[ Hint: Use type() and df.shape ]

In [63]:
mtcars.index = mtcars['name']


In [65]:

type(mtcars)

pandas.core.frame.DataFrame

In [66]:
mtcars.shape

(32, 12)

In [67]:
mtcars.head()

name   mpg  cyl   disp   hp  drat     wt  \
name                                                                       
Mazda RX4                  Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   

                    qsec  vs  am  gear  carb  
name                                          
Mazda RX4          16.46   0   1     4     4  
Mazda RX4 Wag      17.02   0   1     4     4  
Datsun 710         18.61   1   1     4     1  
Hornet 4 Drive     19.44   1   0     3     1  
Hornet Sportabout  17.02   0   0     3     2

In [68]:
mtcars.tail()

name   mpg  cyl   disp   hp  drat     wt  qsec  vs  \
name                                                                           
Lotus Europa      Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   
Ford Pantera L  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   
Ferrari Dino      Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   
Maserati Bora    Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   
Volvo 142E          Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   

                am  gear  carb  
name                            
Lotus Europa     1     5     2  
Ford Pantera L   1     5     4  
Ferrari Dino     1     5     6  
Maserati Bora    1     5     8  
Volvo 142E       1     4     2

In [69]:
mtcars.iloc[:5,:2]

name   mpg
name                                      
Mazda RX4                  Mazda RX4  21.0
Mazda RX4 Wag          Mazda RX4 Wag  21.0
Datsun 710                Datsun 710  22.8
Hornet 4 Drive        Hornet 4 Drive  21.4
Hornet Sportabout  Hornet Sportabout  18.7

In [70]:
# Convert series to panda dataframe

a = pd.Series(['NewYork', 'Japan', 'India'])
index_all = pd.Index([1,2,3])
a.index=index_all
a.to_frame()


0
1  NewYork
2    Japan
3    India